//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.NETMVCCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tt_Transaction
    {
        public int TransactionID { get; set; }
        public int AccountID { get; set; }
        public System.DateTime TransDate { get; set; }
        public string Description { get; set; }
        public string DebitCreditStatus { get; set; }
        public decimal Amount { get; set; }
    }
}
